
---
# optional firewall role
### begin firewall ###
# we need TCP/5666 open
# determine firewall status and take action
# 1) use firewall-cmd if firewalld is utilized
# 2) insert iptables rule if iptables is used

# Firewalld
- name: Determine if firewalld is in use
  shell: systemctl is-enabled firewalld.service | egrep -qv 'masked|disabled'
  ignore_errors: true
  register: firewalld_in_use
  no_log: true
  become: true

- name: Determine if firewalld is active
  shell: systemctl is-active firewalld.service | grep -vq inactive
  ignore_errors: true
  register: firewalld_is_active
  no_log: true
  become: true

- name: Determine if TCP/{{nrpe_tcp_port}} is already active
  shell: firewall-cmd --list-ports | egrep -q "^{{nrpe_tcp_port}}/tcp"
  ignore_errors: true
  register: firewalld_nrpe_tcp_port_exists
  no_log: true
  become: true

# add firewall rule via firewall-cmd
- name: Add firewall rule for TCP/{{nrpe_tcp_port}} (firewalld)
  command: "{{ item }}"
  with_items:
    - firewall-cmd --zone=public --add-port={{nrpe_tcp_port}}/tcp --permanent
    - firewall-cmd --reload
  ignore_errors: true
  become: true
  when: firewalld_in_use.rc == 0 and firewalld_is_active.rc == 0 and firewalld_nrpe_tcp_port_exists.rc != 0

### end firewall settings ###
